=== pypi-data/pypi-mirror-85/packages/ndexutil/ndexutil-0.13.1-py3-none-any.whl/ndexutil/tsv/loading_plan_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "NDEx TSV Loading Plan",
    "description": "Loading plan used by TSV loader",

    "definitions": {

      "NodeMapping": {
        "type": "object",
        "properties": {
          "rep_prefix": {
            "description": "Prefix that need to be added to the id column",
            "type": "string"
          },
          "rep_column": {
           "description": "Column that will be used as the represent field of a node. The first non-empty value in the list will be used to populate the node represent field.",
            "type": "string"
          },
          "node_name_column": {
            "description": "The name of a node. If rep_column is missing in this object, the node_name will be used as a unique id of a node. This version of TSV loader requires node name to be unique in a network",
            "type": "string"
          },
          "property_columns": {
            "description": "Defines the mapping of all node properties. An Each of the non-empty value in these columns ",
            "type": "array",
            "items" : { "oneOf": [
              {"type" : "string"},
              {"type" : "object",
                "properties": {
                  "column_name": {
                      "description": "name of the column in the spreadsheet",
                      "type":"string"
                    },
                  "attribute_name": {
                      "description": "attribute_name this column maps to",
                      "type": "string"
                  },
                  "value_prefix": {
                      "description": "prefix that need to be added to the values of this attributes(without colon).",
                      "type": "string"
                  },
                  "data_type": {
                      "description": "data type of the attribute values, default is string",
                      "type": "string",
                      "enum": ["string", "double", "boolean", "integer" ,"long", "list_of_string",
                          "list_of_double", "list_of_boolean", "list_of_integer", "list_of_long"]
                  },
                  "delimiter": {
                      "description": "delimiter character for array data types",
                      "type": "string"
                  },
                  "default_value": {
                    "description": "default value of this property when column_name is missing or the value in that column is missing",
                    "type": "string"
                  }
                },
                "additionalProperties": false,
                "anyOf": [
                  {
                    "type":"object",
                    "required": ["column_name"]
                  },
                  {
                    "type":"object",
                    "required": ["attribute_name"]
                  }
                ]
              }
             ]
            }
          }

        },
        "additionalProperties": false,
        "anyOf": [
            {
              "type":"object",
              "required": ["rep_column"]
            },
            {
              "type":"object",
              "required": ["node_name_column"]
            }
          ]
      }

    },

    "type": "object",
    "properties": {
        "context": {
          "description": "Declare the namespaces that are used in this TSV file.",
          "type": "object",
           "patternProperties": {
                "^[^/@\\$\\^]+$": {
                  "type": "string",
                  "format": "uniref"
                }
            },
            "additionalProperties": false
        },
        "source_plan": {
            "description": "Mapping of the source nodes",
            "$ref": "#/definitions/NodeMapping"
        },
        "target_plan": {
             "description": "Mapping of the target nodes",
            "$ref": "#/definitions/NodeMapping"
        },
        "edge_plan": {
          "type": "object",
          "properties": {
            "default_predicate": {
              "description": "default value for edge name (interaction name).",
              "type": "string"
            },
            "predicate_id_column": {
              "description": "column that specify the edge name. If the value in this cell is missing, we will use the value defined in 'defalut_predicate', if it exists.",
              "type": "string"
            },
            "predicate_prefix": {
              "type": "string"
            },
            "property_columns": {
              "type": "array",
              "items": { "oneOf": [
              {"type" : "string"},
              {"type" : "object",
                "properties": {
                  "column_name": {
                      "description": "name of the column in the spreadsheet",
                      "type":"string"
                    },
                  "attribute_name": {
                      "description": "attribute_name this column maps to",
                      "type": "string"
                  },
                  "value_prefix": {
                      "description": "prefix that need to be added to the values of this attributes(without colon).",
                      "type": "string"
                  },
                  "data_type": {
                      "description": "data type of the attribute values, default is string",
                      "type": "string",
                      "enum": ["string","double","boolean","integer","long","list_of_string",
                          "list_of_double","list_of_boolean", "list_of_integer", "list_of_long"]
                  },
                  "delimiter": {
                      "description": "delimiter character for array data types",
                      "type": "string"
                  },
                  "default_value": {
                    "description": "default value of this property when column_name is missing or the value in that column is missing",
                    "type": "string"
                  }
                },
                "additionalProperties": false,
                "anyOf": [
                  {
                    "type":"object",
                    "required": ["column_name"]
                  },
                  {
                    "type":"object",
                    "required": ["attribute_name"]
                  }
                ]
              }
             ]
            }
            }
          },
          "additionalProperties": false

        }

    },
    "additionalProperties": false,
    "required": ["source_plan","target_plan","edge_plan"]

}

=== pypi-data/pypi-mirror-85/packages/ndexstringloader/ndexstringloader-1.0.0-py2.py3-none-any.whl/ndexstringloader/string_plan.json
{
    "context":
    {
        "ncbigene": "http://identifiers.org/ncbigene/",
        "uniprot": "http://identifiers.org/uniprot/",
        "ensembl": "http://identifiers.org/ensembl/"
    },
    "source_plan":
    {
        "rep_prefix": "",
        "rep_column": "represents1",
        "node_name_column": "name1",
        "property_columns":
           [
               {
                  "attribute_name": "type",
                  "default_value": "protein"
               },
               {
                   "column_name": "alias1",
                   "attribute_name": "alias",
                   "data_type": "list_of_string",
                   "delimiter" : "|"
               }
           ]
    },

    "target_plan":
    {
        "rep_prefix": "",
        "rep_column": "represents2",
        "node_name_column": "name2",
        "property_columns":
           [
               {
                  "attribute_name": "type",
                  "default_value": "protein"
               },
               {
                 "column_name": "alias2",
                 "attribute_name": "alias",
                 "data_type": "list_of_string",
                 "delimiter" : "|"
             }
           ]
    },

    "edge_plan":
    {
        "default_predicate": "interacts-with",
        "property_columns": [
            {
                "column_name": "neighborhood",
                "data_type": "double"
            },
            {
                "column_name": "neighborhood_transferred",
                "data_type": "double"
            },
            {
                "column_name": "fusion",
                "data_type": "double"
            },
            {
                "column_name": "cooccurence",
                "data_type": "double"
            },
            {
                "column_name": "homology",
                "data_type": "double"
            },
            {
                "column_name": "coexpression",
                "data_type": "double"
            },
            {
                "column_name": "coexpression_transferred",
                "data_type": "double"
            },
            {
                "column_name": "experiments",
                "data_type": "double"
            },
            {
                "column_name": "experiments_transferred",
                "data_type": "double"
            },
            {
                "column_name": "database",
                "data_type": "double"
            },
            {
                "column_name": "database_transferred",
                "data_type": "double"
            },
            {
                "column_name": "textmining",
                "data_type": "double"
            },
            {
                "column_name": "textmining_transferred",
                "data_type": "double"
            },
            {
                "column_name": "combined_score",
                "data_type": "double"
            }

        ]
    }
}

=== pypi-data/pypi-mirror-85/packages/ndexbiogridloader/ndexbiogridloader-1.0.0-py2.py3-none-any.whl/ndexbiogridloader/organism_load_plan.json
{
    "context":
    {
        "ncbigene": "http://identifiers.org/ncbigene/",
        "pubmed":  "http://identifiers.org/pubmed/"
    },
    "source_plan":
    {
        "rep_column": "Entrez Gene Interactor A",
        "rep_prefix": "ncbigene",
        "node_name_column": "Official Symbol Interactor A",
        "property_columns":
           [
             {"column_name": "Organism Interactor A",
                "attribute_name": "Organism Taxon Id"},

             {  "column_name": "Synonyms Interactor A",
                "attribute_name": "alias",
                "delimiter" : "|" },

            {
                "attribute_name": "type",
                "default_value": "protein"
            }
           ]
    },
    "target_plan":
    {
        "rep_column": "Entrez Gene Interactor B",
        "node_name_column": "Official Symbol Interactor B",
        "rep_prefix": "ncbigene",
        "property_columns":
           [
              {"column_name": "Organism Interactor B",
                "attribute_name": "Organism Taxon Id"},

             {  "column_name": "Synonyms Interactor B",
                "attribute_name": "alias",
                "delimiter" : "|"
             },
             {
                "attribute_name": "type",
                "default_value": "protein"
             }
           ]
    },
    "edge_plan":
    {
        "default_predicate": "interacts-with",
        "property_columns": [
               {
                    "column_name": "Experimental System",
                    "delimiter": "|"
               },
               {
                    "column_name": "Experimental System Type",
                    "data_type": "list_of_string"
               },
               {
                    "column_name": "Pubmed ID",
                    "attribute_name": "citation",
                    "value_prefix": "pubmed",
                    "delimiter": "|"
               },
               {
                    "column_name": "Throughput",
                    "data_type": "list_of_string"
                },
               {
                    "column_name": "Score",
                    "data_type": "list_of_double"
                },
               {
                    "column_name": "Modification",
                    "delimiter": "|"
                },
               {
                    "column_name": "Phenotypes",
                    "delimiter": "|"
                },
               {
                    "column_name": "Qualifications",
                    "delimiter": "|"
                }

        ]
    }
}
